[project]
name = "hat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "google-genai>=1.20.0",
    "googlesearch-python>=1.3.0",
    "python-dotenv>=1.1.0",
]
